version: "3.8"
services:
  dev: &dev
    # build: .
    build:
      context: .
      dockerfile: Dockerfile
      args:
        arg1: 1
    init: true
    # user: nobody
    volumes:
      - .:/app
      # - /Users/sam/Work/CodeProjects/exif-manager/data:/app/mount:rw
      - /Volumes/Sam/Pictures/Camera Roll:/app/mount:rw
    command: sleep infinity

  app:
    <<: *dev
    profiles:
      - not_started_automatically
    command: python3.12 src/main.py
